apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: project
  labels:
    app: flask
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
