apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: project
  labels:
    app: front-end
spec:
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
